name: Install, Build & Run Cypress

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn
      - name: Install & Build Backend
        run: |
          git clone git@github.com:freesewing/backend
          cd backend
          yarn install
          yarn global add backpack-core
          yarn build
      - name: Build
        run: yarn build
      - name: Run Cypress
        run: yarn start-and-test
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          LANGUAGE: en
