# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      CI: true    
      GATSBY_LANGUAGE: en
      GATSBY_FRONTEND: 'http://localhost:9000/'
      GATSBY_BACKEND: "https://backend.freesewing.org/"
      GATSBY_TILER: "https://tiler.freesewing.org/" 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12      

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn serve
          spec: cypress/integration/people.spec.js          

      # Test run screenshots are captured only on failures
      - name: Store screenshot artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run videos are always captured
      - name: Store video artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos          